apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../optional

images:
- name: jaybee-lab/backend
  newName: ghcr.io/shinjbin/jaybee-lab-backend
  newTag: sha-7ce4d53321f5cbd38582e1827427fdd7640c5b2d
- name: jaybee-lab/bitcoin-trader
  newName: ghcr.io/shinjbin/jaybee-lab-bitcoin-trader
  newTag: sha-7ce4d53321f5cbd38582e1827427fdd7640c5b2d
- name: jaybee-lab/frontend
  newName: ghcr.io/shinjbin/jaybee-lab-frontend
  newTag: sha-7ce4d53321f5cbd38582e1827427fdd7640c5b2d

patches:
- path: backend-replicas-patch.yaml
- path: worker-replicas-patch.yaml
- path: cloudflared-replicas-patch.yaml
- path: bitcoin-trader-replicas-patch.yaml
