apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../optional

images:
- name: jaybee-lab/backend
  newName: ghcr.io/shinjbin/jaybee-lab-backend
  newTag: sha-69b52cd67a0e6fefa32c4543b354d0b68fe9d88a
- name: jaybee-lab/bitcoin-trader
  newName: ghcr.io/shinjbin/jaybee-lab-bitcoin-trader
  newTag: sha-69b52cd67a0e6fefa32c4543b354d0b68fe9d88a
- name: jaybee-lab/frontend
  newName: ghcr.io/shinjbin/jaybee-lab-frontend
  newTag: sha-69b52cd67a0e6fefa32c4543b354d0b68fe9d88a

patches:
- path: backend-replicas-patch.yaml
- path: worker-replicas-patch.yaml
- path: cloudflared-replicas-patch.yaml
- path: bitcoin-trader-replicas-patch.yaml
