apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: jaybee-lab
spec:
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
