apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaybee-lab-prod
  namespace: argocd
spec:
  project: jaybee-lab
  source:
    repoURL: https://github.com/shinjbin/jaybee-lab.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: jaybee-lab
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
