apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jaybee-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Jaybee Lab production workloads
  sourceRepos:
    - https://github.com/shinjbin/jaybee-lab.git
  destinations:
    - namespace: jaybee-lab
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
